In [8]:
# General libraries

import csv 
import pandas as pd
from pandas import DataFrame 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import *

# Feature Selection

from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

# Decision Tree Algorithm

from sklearn.tree import DecisionTreeClassifier 

# Progrom optimization

import numba
from numba import jit

In [9]:
@jit # increase the computation speed of the program

def training(train , test):
    df_train = pd.DataFrame.from_csv(train)
    df_test = pd.DataFrame.from_csv(test)
    print(df_train.shape)
    print(df_test.shape)

    # Replacing strings with numericals for better classification

    df_train = df_train.replace('LAYING','1')
    df_train = df_train.replace('SITTING','2')
    df_train = df_train.replace('STANDING','3')
    df_train= df_train.replace('WALKING','4')
    df_train = df_train.replace('WALKING_DOWNSTAIRS','5')
    df_train = df_train.replace('WALKING_UPSTAIRS','6')
    
    df_test = df_test.replace('LAYING','1')
    df_test = df_test.replace('SITTING','2')
    df_test = df_test.replace('STANDING','3')
    df_test=  df_test.replace('WALKING','4')
    df_test = df_test.replace('WALKING_DOWNSTAIRS','5')
    df_test = df_test.replace('WALKING_UPSTAIRS','6')
    
    target = df_train.Activity
    df_train = df_train.drop(['Activity'],axis=1)
    features = df_train.columns
    
    
    estimator = LinearRegression()
    selector = RFE(estimator , 22 , step=1 )
    selector = selector.fit(df_train,target)
    features = df_train.columns
    ranking = selector.ranking_
    
    a = (sorted(zip(map(float, ranking), features)))
    
    ## Grouping all the features that has rank more than 251 to remove it from the original dataset

    f = []
    rows = np.arange(561)
    for i in rows :
            b = a[i]
            print(b)
            if b[0] > 251:
                f.append(b[1])
            else :
                print('Feature important')
                
    # Dropping of those columns

    df_train = df_train.drop(f,axis=1)
    df_test = df_test.drop(f,axis=1)

    # Creating the target variable for the test dataset

    target_t = df_test.Activity
    df_test = df_test.drop('Activity',axis=1)
    
    # Training Dataset

    dtc = DecisionTreeClassifier(max_depth = 250)
    dtc_train = dtc.fit(df_train , target)
    dtc_predict_train = dtc.predict(df_train)
    
    # Calculating Metrics
    
    score_train = accuracy_score(target , dtc_predict_train)
    cm_train = confusion_matrix(target ,dtc_predict_train)
    print(score_train)
    print(cm_train)
    
    # Test Dataset

    dtc_test = dtc.fit(df_test , target_t)
    dtc_predict_test = dtc.predict(df_test)
    
    # Calculating Metrics
    
    score_test = accuracy_score(target_t , dtc_predict_test)
    cm_test = confusion_matrix(target_t ,dtc_predict_test)
    print(score_test)
    print(cm_test)
    
    pickle.dump(dtc ,open('BEST_MODEL_HAR.pkl', "wb" ))
    
training('train.csv','test.csv')

(7352, 562)
(2947, 562)
(1.0, 'fBodyAcc-bandsEnergy()-25,32.1')
Feature important
(1.0, 'fBodyAcc-bandsEnergy()-25,48.1')
Feature important
(1.0, 'fBodyAcc-bandsEnergy()-33,40.1')
Feature important
(1.0, 'fBodyAcc-bandsEnergy()-33,48.1')
Feature important
(1.0, 'fBodyAcc-bandsEnergy()-41,48.1')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-17,24')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-17,24.2')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-17,32')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-17,32.2')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-25,32.2')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-25,48')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-33,40')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-33,48')
Feature important
(1.0, 'fBodyAccJerk-bandsEnergy()-41,48')
Feature important
(1.0, 'fBodyGyro-bandsEnergy()-1,16.1')
Feature important
(1.0, 'fBodyGyro-bandsEnergy()-1,24')
Feature important
(1.0, 'fBodyGyro-bandsEner

1.0
[[537   0   0   0   0   0]
 [  0 491   0   0   0   0]
 [  0   0 532   0   0   0]
 [  0   0   0 496   0   0]
 [  0   0   0   0 420   0]
 [  0   0   0   0   0 471]]
